theme: minima
title: My page
author: Ayşe
email: ayse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  new desc

# social links
twitter_username: nogithub account # DO NOT include the @ character, or else the build will fail!
github_username:  ayyse # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
